# Generated by Django 4.1.2 on 2022-11-21 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0019_alter_category_id_alter_dow_id_alter_mycart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dow',
            name='product',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saler.product', verbose_name='رقم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='saler.category', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='salerdetail',
            name='state',
            field=models.CharField(choices=[('اليمن', 'اليمن'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wholesaleproduct',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='saler.category', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='wholesaleproduct',
            name='color',
            field=models.TextField(verbose_name='أدخل اللون مفصولة بفاصلة'),
        ),
        migrations.AlterField(
            model_name='wholesaleproduct',
            name='size',
            field=models.TextField(verbose_name='الحجم المتاح (مفصولة بفاصلة)'),
        ),
    ]
